project:
  type: website
  output-dir: docs
  render: 
    - "*.qmd"

execute: 
  freeze: auto
  
website:
  title: "Applied Data Science for Cities"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: syllabus/index.qmd
        text: "Syllabus"
      - href: lectures/index.qmd
        text: "Lectures"
      - href: labs/index.qmd
        text: "Labs"
      - href: howto/index.qmd
        text: "How To"
      - href: resources/index.qmd
        text: "Resources"
    search: true
  favicon: favicon.png
  page-footer:
    right: "Made with R and [Quarto](https://quarto.org/)"

  sidebar:
    - title: "Lectures"
      contents:
        - section: "Lectures"
          contents:
            - text: "01 What does urban data science do" 
              file: lectures/index.qmd
            - text: "02 Population and Census"
              file: lectures/lecture2.qmd
            - text: "03 Neighborhood Dynamics"
              file: lectures/lecture3.qmd
            - text: "04 Place Opportunity"
              file: lectures/lecture4.qmd
            - text: "05 Accessibility Analysis"
              file: lectures/lecture5.qmd
            - text: "06 Web Storytelling"
              file: lectures/lecture6.qmd


    - title: "Labs"
      contents:
        - section: "Labs"
          contents:
            - text: "01 Data wrangling + visualization pipeline"
              file: labs/index.qmd
            - text: "02 More data-wrangling tools"
              file: labs/lab2.qmd
            - text: "03 Enhanced Visualization"
              file: labs/lab3.qmd
            - text: "04 Describe neighborhood characteristics"
              file: labs/lab4.qmd
            - text: "05 Work with GTFS"
              file: labs/lab5.qmd
            - text: "06 Shiny Apps and Dashboards"
              file: labs/lab6.qmd

    
    - title: "How To"
      contents:
        - section: "Get Started"
          contents:
            - text: "Introduction"
              file: howto/index.qmd
            - text: "Set Up R and RStudio"
              file: howto/setupr.qmd
        - section: "Share Your Work"
      

    - title: "Resources"
      contents:
        - section: "Overview"
          contents:
            - resources/index.qmd
        - section: "Resources"
          contents:
            - text: "Textbooks"
              file: resources/textbook.qmd
            - text: "Urban Data Analysis"
              file: resources/analysis.qmd
            - text: "Data Sources"
              file: resources/data.qmd
            - text: "Inspiration"
              file: resources/inspiration.qmd

format:
  html:
    theme:
      light: [flatly]
    css: 
      - styles.css
    toc: true

editor: visual